version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  browser-tools: circleci/browser-tools@1.0.1

jobs:      
  test:
    docker:
      - image: cimg/ruby:2.7.1
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: Berezhok
          POSTGRES_DB: todo_api_test
      - image: circleci/redis:latest
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: Berezhok
      RAILS_ENV: test
    steps:
      - checkout 
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Run redis
          command: sudo redis-server --daemonize yes
      - run:
          name: Run Specs
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec
  lintering:
    docker:
      - image: cimg/ruby:2.7.1
    steps:
      - checkout
      - ruby/install-deps
      - run: 
          name: rubocop
          command: bundle exec rubocop

workflows:
  version: 2
  build_and_test:     
    jobs:
      - lintering
      - test:         
          requires:
            - lintering
